language: minimal

services:
  - docker

before_install:
  - docker build . -t mrcide/individual:ci -f docker/Dockerfile.ci

script:
  - docker run --rm -v $(pwd):/opt -w /opt mrcide/individual:ci R CMD build --no-build-vignettes .
  - docker run --rm -v $(pwd):/opt -w /opt -e _R_CHECK_FORCE_SUGGESTS_=0 mrcide/individual:ci R CMD check --no-manual --ignore-vignettes --no-manual $(ls individual_*.tar.gz)
