dist: bionic
sudo: require
language: r

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - g++ -v
