on:
  push:
    branches:
      - master

jobs:
  deploy_static_site:
    runs-on: ubuntu-latest
    name: Deploy github pages
    steps:
      - uses: actions/checkout@v2
      - uses: mrc-ide/pkgdown-action@v1

